[features]
seeds = false
skip-lint = true

[programs.localnet]
tower_game = "ETSyyt4YEy9d3dLNuY2Qb6wCxnv3pRPjJSG8CHtsWLJX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://testnet.dev2.eclipsenetwork.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"

[workspace]
types = "idl/"
